// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPU0lB-lx1NFrpO3IWPGxxSNR4J516XGk',
    appId: '1:717978509782:android:f8a5b1695c6dd64fad0477',
    messagingSenderId: '717978509782',
    projectId: 'myapp-95e87',
    databaseURL: 'https://myapp-95e87-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-95e87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCz6MsUeijvhexc4UlKFHagn6eocyNJO0',
    appId: '1:717978509782:ios:f4edcce1a1ddd08aad0477',
    messagingSenderId: '717978509782',
    projectId: 'myapp-95e87',
    databaseURL: 'https://myapp-95e87-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-95e87.appspot.com',
    iosClientId: '717978509782-2ifcr46m5vsjqt2t1rqq78c1rh7f3cu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiveDollarLunch',
  );
}
